# Generated by Django 5.0.3 on 2024-12-04 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='nombre',
        ),
        migrations.AddField(
            model_name='contacto',
            name='apellidos',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='celular',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='nombres',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
