# Generated by Django 5.0.3 on 2024-11-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.TextField(default='valor predeterminado', max_length=200, verbose_name='nombre'),
        ),
    ]
